[package]
name = "farmap"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
serde = {version = "1.0.217", features =["derive"]}
serde-jsonlines = "0.7.0"
serde_json = "1.0.137"
thiserror = "2.0.11"
